### ISSUE TITLE
Add support for Intersect RFT output

### ISSUE THREAD

**Issue by carve11** [equinor/ecl2df#106]
I have tried to use `ecl2df` on `ascii` RFT output from Intersect (IX), but I get an error. Some assests use IX and it would fantastic if `ecl2df` could support IX output.

I can supply IX RFT output file for anyone to work on this.

I have been able to modify the code in order to read IX RFT data wihout any error. But I do not know if this breaks reading Eclipse RFT data

**Comment by berland** [comment]
If you have a small anonymized binary file example (for inclusion in the test code) that libecl reads well, this might get implemented.  The automated test code should ensure reading E100 RFT data is not broken.

**Comment by carve11** [comment]
When I read your comment more closely and used a binary rft output from IX, then ecl2df seems to work as expected. Sorry about the confusion.
