### ISSUE TITLE
Bundle necessary binaries?

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/ecl2df#116]
It would be awesome 😎 if you could do `pip install ecl2df` and get going, both in small and large projects.

Would it be feasible, and within scope, to bundle necessary compiled binaries from `opm-common` with `ecl2df`? I.e. do the compilation within the continuous deployment step of `ecl2df` on e.g. Travis / GitHub actions / AppVeyor?

Reading https://github.com/OPM/opm-common/issues/1210, it might take some time before that is closed. In addition, talking to the `opm` developers, the Python bindings in `opm.io` is more seen as a tool for the `opm` developers when debugging/developing the Flow simulator ecosystem. Thus, even if the bindings are deployed to `PyPI`, there is a likelihood that it will not follow a semantic versioning system (but rather follow the release cycle of `opm` itself, e.g. twice per year and something of the form `2020.01`).

If they are bundled together with `ecl2df`, `ecl2df` can effectively pin the compiled binaries used.

**Comment by markusdregi** [comment]
I would say that the best way to go forward with this would be to come up with a suggestion to the OPM community where we can assist in setting up a `PyPI` deploy of the Python bindings from their repository given that they are willing to maintain it afterwards. This would benefit not only `ecl2df`, but also other projects that depending on the python bindings :)

That their API is not stable is not necessary a "problem" in this case, as they could just roll a new `0.x` version of the Python bindings each time they release a new release of `flow`. But again, this needs to be discussed together with the OPM developers.

This could potentially be funded by the fmu-dev money... We have not started on these tasks yet, but will do so soon. This will probably not end up in the first batch of work, but Eivind is the one prioritising ;)

**Comment by anders-kiaer** [comment]
Rumors say that `opm-io` would be on PyPI in a not too distant future. Closing this.
