### ISSUE TITLE
[summary] Pandas  time specifier support in summary

### ISSUE THREAD

**Issue by berland** [equinor/ecl2df#181]
fmu-ensemble, which has duplicated summary code with ecl2df, has just gotten support for all pandas time specifiers for interpolation in time, and also the mnemonic 'weekly'. This should be added to ecl2df.

Alternatively refactor fmu-ensemble to use ecl2df for this parsing, see https://github.com/equinor/fmu-ensemble/issues/166

**Comment by miroine** [comment]
have u tried using the time_range attribute from EclSum in ecl.summary ... there u can interpolate with any kind of timeframe --> weekly is just "7D"

**Comment by berland** [comment]
Not tried, but this will also be possible by implementing the pandas mnemonics; see examples: https://github.com/equinor/fmu-ensemble/blob/dcda53e1e19de1a29480b415939ace6eb63ca0e6/tests/test_ensemble.py#L406
