### ISSUE TITLE
Defaulted COMPDAT data not parsed correctly

### ISSUE THREAD

**Issue by wouterjdb** [equinor/ecl2df#187]
It is possible in a DATA deck to default (either `1*` or `0`) the I and J coordinate in the `COMPDAT` keyword. The I and J coordinates will then be interpreted as being the same as the I and J coordinates of the well head, as defined in the `WELSPECS` keyword.

ecl2csv will interpret a default I or J coordinate in COMPDAT as a zero and will not do the translation. Leading to an incorrect I and J coordinate (I=0, J=0) in the export.

**Comment by berland** [comment]
Hmm, parsing the defaults correctly was supposed to be the responsibility of `opm-common`. Bug there?

**Comment by berland** [comment]
I get it, `0` is a valid coordinate in the `COMPDAT` record, then it is the responsibility of the application using `COMPDAT` to replace zeros with information from `WELSPECS`.

`opm-common` returns `0` for defaulted coordinates.
