### ISSUE TITLE
[gruptree] Error when using gruptree on a specific datadeck

### ISSUE THREAD

**Issue by carve11** [equinor/ecl2df#197]
Tried to run `ecl2csv gruptree` on a E300 datadeck but it fails with the following error

```
[2020.09.02-py36] [d01jg@st-linrgsn321 model]$ ecl2csv gruptree --prettyprint R3-TEST-COM-167.DATA
Traceback (most recent call last):
  File "/prog/res/komodo/2020.09.02-py36/root/bin/../libexec/ecl2csv", line 11, in <module>
    sys.exit(main())
  File "/prog/res/komodo/2020.09.02-py36/root/lib/python3.6/site-packages/ecl2df/ecl2csv.py", line 254, in main
    args.func(args)
  File "/prog/res/komodo/2020.09.02-py36/root/lib/python3.6/site-packages/ecl2df/gruptree.py", line 293, in gruptree_main
    dframe = deck2df(eclfiles.get_ecldeck(), startdate=args.startdate)
  File "/prog/res/komodo/2020.09.02-py36/root/lib/python3.6/site-packages/ecl2df/eclfiles.py", line 97, in get_ecldeck
    deck = opm.io.Parser().parse(deckfile, parsecontext)
ValueError: 
Failed to parse keyword: SWOF
In file /scratch/trestakk/rasha/r3_rnb21_sens_oldsurf/realization-167/eclipse/include/props/swof.inc, line 1

Error message: Malformed floating point number 'INCLUDE'
```

Not sure if E300 datadecks are not supported but a bit strange to fail on SWOF?

Using /prog/res/komodo/2020.09.02-py36/root/bin/python

**Comment by berland** [comment]
Can you make the error reproducible on a simpler deck and add it to the issue?

**Comment by carve11** [comment]
OK, I have attached a E300 datadeck where I have commented out all the INCLUDE and only pasted include contents where `ecl2csv gruptree` failed. It fails on the SWOF, SGOF and some PVT kw. 

[R3-TEST-167_GRUPTREE.zip](https://github.com/equinor/ecl2df/files/5516193/R3-TEST-167_GRUPTREE.zip)

**Comment by berland** [comment]
TABDIMS says NTSFUN is 4, while the SWOF data provided is only for one SATNUM. 

The error can be fixed by setting NTSFUN to 1.

**Comment by carve11** [comment]
OK, but then `ecl2csv` is more strict than `e300`? I mean, Eclipse does not fail but simulate the data deck without any issues. It might warn me that I allocate more memory than needed, but it runs any way. If I am not mistaken `GRUPTREE`, `GRUPNET` and `WELSPECS` are all `SCHEDULE` section kw, why is it needed to check and fail on the other sections?

**Comment by berland** [comment]
That is correct. `ecl2df` uses the parser from https://opm-project.org (the `flow` reservoir simulator), and reproducing E100's and E300 tolerance towards user errors has proven very hard, and is not prioritized. E300 probably gives a warning on your case.

(`TABDIMS`  is not only about memory allocation, it also defines how the deck should be parsed, when a keyword's data section ends etc.)
