### ISSUE TITLE
Make ert an optional dependency?

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/ecl2df#209]
...if so, this is useful for those not using ERT, but only ecl2df in :cloud: or in other contexts. ERT again depends on some big dependencies like PyQT.

**Comment by berland** [comment]
This has been supported earlier, but then for the sake of Python 2 support: https://github.com/equinor/ecl2df/blob/31465eeb3ef69fa9b5e49bc63de2031503e4a7c2/tests/test_hook_implementations.py#L8

**Comment by anders-kiaer** [comment]
I can give this one a try - if we want to make it an optional dependency. Looking at https://github.com/equinor/ecl2df/search?q=ert it looks like it's not many files that needs to be changed.

Do we want `ert` to be an official "extra" dependency in `setup.py`, like `pip install ecl2df[ert]`, or does that feel unnecessary given that the extra group contains only one package (`ert`)?

**Comment by berland** [comment]
`pip install ecl2df[ert]` could be nice.
