### ISSUE TITLE
ValueError: A WELOPEN keyword is not acting on any existing connection

### ISSUE THREAD

**Issue by tklov11** [equinor/ecl2df#211]
Hi,
The Gina Krog model has a top level schedule file including a nested schedule file for the prediction phase (see link to .DATA file below). I import the top level schedule file from the model catalogue using the commands

```python
import ecl2df
deck = ecl2df.EclFiles.file2deck(../include/SCH/schedulefile)
compdfs = ecl2df.compdat.deck2df(deck)
```

I get the following error in the current version on Github:

```
Traceback (most recent call last):
File "", line 1, in
File "/private/tklov/monty/root/lib/python3.6/site-packages/ecl2df/compdat.py", line 185, in deck2dfs
compdat_df = applywelopen(compdat_df, welopen_df)
File "/private/tklov/monty/root/lib/python3.6/site-packages/ecl2df/compdat.py", line 382, in applywelopen
"(I=%s,J=%s,K=%s)" % (row["I"], row["J"], row["K"])
ValueError: A WELOPEN keyword is not acting on any existing connection. (I=None,J=None,K=None)
```

I do not get any error in the Komodo-version of ecl2df. Further, as you see in the link below, the nested include file has a file path referenced from the /model/ folder. If I remove the path-part of the INCLUDE (../include/SCH/), ecl2df works fine with the commands above. However, I want to use the .DATA deck as prepared by the GK-team.

Link:
.DATA file: /scratch/gina_krog/mpic/AICD_B5/eclipse-0/model/GINAKROG_PRED0_B5_WELL3_NEWPARAM.DATA

**Comment by berland** [comment]
Can you provide a minimal shareable example that triggers this bug? (few people should have access to /scratch/gina_krog)

**Comment by berland** [comment]
This is triggered in https://github.com/equinor/ecl2df/blob/74d32f6862887e3b9292cc45afd5418f7e3be044/ecl2df/compdat.py#L379
and seems ok from code inspection.

A critical question is whether there are any COMPDAT records in the input prior to the WELOPEN keyword that triggers the exception. If there are none, the  failure seems warranted, but Eclipse 100 will maybe happily ignore it (warning emitted from Eclipse?). If so, the fix is either to fix the input, or to downgrade this exception to a warning.

Ping @wouterjdb

**Comment by berland** [comment]
This is most likely related to `k` indices provided in `WELOPEN` that maybe ranges over more `k-indices that  what is present in `COMPDAT`, a situation which is probably a warning in Eclipse. This should be degraded from a ValueError to a warning message.

**Comment by tklov11** [comment]
A WELOPEN statement for a list halts the program. The list is defined after COMPDAT, which again has a definition of all wells in the list. 

WELOPEN                                                                                                              
  '*GI_LIST'  SHUT  /                                                                                                
/

**Comment by berland** [comment]
There is also a `test_welopen.py`

**Comment by tklov11** [comment]
I cannot see a test for WELOPEN '*list' there either.

**Comment by berland** [comment]
Ah, "list of wells". No, that is not supported at all by ecl2df currently. So compdat must recognize when well-lists are in use, and either support or ignore that too.

**Comment by berland** [comment]
#312 has now been merged, WLIST is now supported and will be used by WELOPEN.
