### ISSUE TITLE
[summary] Add metadata-support

### ISSUE THREAD

**Issue by berland** [equinor/ecl2df#241]
fmu-ensemble can read metadata from a UNSRMY/SMSPEC file.

https://github.com/equinor/fmu-ensemble/blob/d4bca3b9b6ff8240b70512f2199ba1b27293953f/src/fmu/ensemble/realization.py#L1116

This should be supported by ecl2df also. Suggest to use the `.attrs` attribute in pandas dataframes to add a similar dictionary as metadata for returned dataframe objects. The operation should be cheap enough to be added by default, if not triggered by an option.

**Comment by asnyv** [comment]
We need to be a little bit careful with `.attrs` considering it is experimental and may change without warning 🥴
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.attrs.html

**Comment by asnyv** [comment]
A safe alternative is of course a tuple of the DataFrame and a `dict` if you set a flag, even though `.attrs` is neat as is.

**Comment by berland** [comment]
That would have to be in a different function than `summary.df()`, as that function should only return a Dataframe and nothing else. But adding an extra function to the API is a valid backup solution that would work irrespective of changes in Pandas.

**Comment by berland** [comment]
This is still experimental in Pandas and blew up in https://github.com/equinor/res2df/issues/507
