### ISSUE TITLE
Export units

### ISSUE THREAD

**Issue by lindjoha** [equinor/ecl2df#300]
My specific problem is that I need the unit of the KH in the compdat export. I suggest a metadata export with units of different input and output.

**Comment by berland** [comment]
Could this suffice?
```
In [7]: from ecl2df import EclFiles
In [8]: "METRIC" in  EclFiles("reek/eclipse/model/2_R001_REEK-0.DATA").get_ecldeck()
Out[8]: True
```

**Comment by lindjoha** [comment]
Yes, I suppose that is an easy solution. What about a `get_unit_system` - function in `EclFiles`?

**Comment by berland** [comment]
Maybe not in EclFiles, as that is supposed to just represent the collection of Eclipse files, and not trying to present an API for an Eclipse deck. Meaning, there is no natural location in `ecl2df` for such a function (yet?). 

Adding this kind of support to ecl2df switches the scope of ecl2df into a Python API for the entire deck, which would have consequences for further feature requests..

**Comment by lindjoha** [comment]
Ok, I see.
