### ISSUE TITLE
Problems with the OP/SH column of the COMPDAT export.

### ISSUE THREAD

**Issue by lindjoha** [equinor/ecl2df#301]
I have used the COMPDAT export as input to the WellCompletions plugin in Webviz and I have noticed a few problems.

It is quite common that all the COMPDAT data is put in the beginning of the schedule-file, even though the well is not actually opened until later. It seems like the OP/SH column is set to OPEN in this case even if the well is SHUT with WCONPROD at the same timestep (and then later opened with WELOPEN). 

If the wells are later closed with the WELOPEN keyword, then the completions are correctly set to SHUT in the export. But if only parts of the well are SHUT using WELOPEN and referring to specific COMPLUMPs then the completions are not set to SHUT in the export (see example from Johan Castberg below).

WELOPEN
 SWI02  SHUT  3*  7  7  /
 SWI02  SHUT  3*  8  8  /
 SWI02  SHUT  3*  9  9  /
/

**Comment by berland** [comment]
WCONPROD-shutting in the compdat dataframe is a missing feature.

COMPLUMP support is also missing, and the example above will error hard in #298

**Comment by lindjoha** [comment]
Made new issue for only the COMPLUMP part #332

**Comment by lindjoha** [comment]
Made new issue for the WCONPROD feature: #335. Closing this.
