### ISSUE TITLE
[grid] Return floating point columns as float64 for stable summation

### ISSUE THREAD

**Issue by berland** [equinor/ecl2df#316]
The floating point colums returned by `grid.df()` are of type `float32`, as that is the precision used in libecl.

When arrays of float32 are summed naively, using  `.sum()`, this results in inaccuracies, see for example https://en.wikipedia.org/wiki/Kahan_summation_algorithm

If the user always uses `math.fsum()`, this is not a problem, and the user should maybe always do that.

Still, by sacrificing memory, and converting the arrays to float64, `.sum()` will be as accurate as `math.fsum()` in test cases.

As knowlegde of numerical summation problems and floating point is not widespread, this might be worth it.

**Comment by berland** [comment]
```
In [76]: ef.get_initfile().iget_named_kw("PORV", 0).numpyView().sum()
Out[76]: 399077440.0

In [77]: math.fsum(ef.get_initfile().iget_named_kw("PORV", 0).numpyView())
Out[77]: 399077424.9251621

In [78]: ef.get_initfile().iget_named_kw("PORV", 0).numpyView().astype(float).sum()
Out[78]: 399077424.9251621
```

**Comment by berland** [comment]
ping @asnyv, @jcrivenaes

**Comment by asnyv** [comment]
I am very skeptical to doubling memory usage just to remove errors in the 8th digit. The input precision is anyways not higher, so the added value by increasing precision of the output is marginal. 

We already struggle with memory consumption when handling ensembles of simulations, and grid data may get big, so I don't think this is worth it.

additional input @anders-kiaer @sigurdp ?

**Comment by sigurdp** [comment]
I'm not sure I have the full context here, but I tend to agree with @asnyv. Faced with the memory consumption issues we are having, we should be very careful about further increasing the memory footprint.

Dont have any "hands-on" experience, but could `.sum(dtype=np.float64)` be a solution?
The caller still needs to be aware of the potential problem though.

**Comment by anders-kiaer** [comment]
FWIW `numpy` mentions float summation in their documentation, so non-professional scripters at least have a chance of seeing the float problem stated there 😄 
- https://numpy.org/doc/stable/reference/generated/numpy.mean (see Notes section)
- https://numpy.org/doc/stable/reference/generated/numpy.sum (see Notes section)

Maybe the problem (scripters not being aware) can be mitigated by giving a note/`dtype=np.float64` example also in `ecl2df` documentation close to where `grid.df()` is documented, and keeping memory consumption down at the native level?

**Comment by berland** [comment]
Thanks for input. I suggest to not change the dtype, but mention it in the documentation.

**Comment by jcrivenaes** [comment]
It has to be something more than dtype float32 from libecl, since computation using xtgeo, ecl2df and libecl gives _ecl2df as an outlier_: 

```
PORV from XTGeo    : 551052582.59 (np.sum)  551052582.59 (math.fsum)  dtype is float64 
PORV from ecl2df   : 551052608.00 (sum())   551052582.59 (math.fsum)    551052608.00 (np.sum)  dtype is float32
PORV from (lib)ecl : 551052544.00 (np.sum)  551052582.59 (math.fsum) dtype is float32
```
Code is here: /scratch/fmu/jriv/porv_test.py

**Comment by jcrivenaes** [comment]
`np.sum(dframe["PORV"].values.astype(np.float64))` will work with no persistent memory overhead

**Comment by anders-kiaer** [comment]
> `np.sum(dframe["PORV"].values.astype(np.float64))` will

If to be used as an example in the documentation, maybe this should then work as well and use even less (temp.) memory (i.e. only `np.float64` for the output number/accumulator)?
```python
np.sum(dframe["PORV"].values, dtype=np.float64)
```
Or if to keep it short:
```python
dframe["PORV"].values.sum(dtype=float)
```

**Comment by berland** [comment]
> It has to be something more than dtype float32 from libecl, since computation using xtgeo, ecl2df and libecl gives _ecl2df as an outlier_:

Probably correct. If float64 is enough to solve the summation issues, it is by luck, since floating point summation is as problematic for float64 as for float32, just at another level. `math.fsum()` is the robust solution, adding floats is always susceptible to roundoff errors.

**Comment by berland** [comment]
> (Apparently `.values` [is not recommended anymore](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.values.html) for some reason, instead `.to_numpy()` is suggested?)

See https://pandas.pydata.org/pandas-docs/stable/user_guide/basics.html#attributes-and-underlying-data (scroll down a bit)

(this was new to me!)
