### ISSUE TITLE
Files are not properly closed after opened?

### ISSUE THREAD

**Issue by nervhjc** [equinor/ecl2df#337]
We are using ecl2df for a research project. Thanks for the great work and the willingness to share! 

We notice that after we use ecl2df to read an egrid or init file (like with the code below), python create a read file descriptor for the file and never really close it. This results in a large number of file descriptors created after several read operations (see pic below). The file descriptors prevent the .EGRID, .INIT, and .UNRST files from being deleted. 

eclfiles = ecl2df.EclFiles(self.dest_path+"/drl_ix")
df = ecl2df.grid.init2df(eclfiles)

Is there a way to properly close the files after one is done reading. Something like eclfiles.close()? Thanks. 

![image](https://user-images.githubusercontent.com/61808321/127576122-7e73eb71-4164-4a3e-a6f6-eb5305ea5c25.png)

**Comment by berland** [comment]
Thanks for the report. This is probably a bug or missing feature in ecl2df and should be resolved. PRs are welcome.
