### ISSUE TITLE
Tests fail with Pandas 1.4.0

### ISSUE THREAD

**Issue by berland** [equinor/ecl2df#399]
`test_parameters::test_load` will fail with Pandas 1.4.0, as that Pandas version seems quite ok with parsing text files with more fields than what it has column names for. Pandas <1.4.0 gives a ParserError.

Solutions: 
1. Pin Pandas < 1.4.0
2. Make `pd.read_csv()` in `ecl2df.parameters.load_parameterstxt` behave as strictly as needed.
3. Relax the testing, not try to capture all error scenarios with parameters.* this early.

**Comment by asnyv** [comment]
Closed by #411
