### ISSUE TITLE
[rft] Extract simulated well pressures at (x,y,z,time) or (well,md,time)

### ISSUE THREAD

**Issue by berland** [equinor/ecl2df#41]
This is planned as convenience function in the `rft2df` submodule.

Features:
* If x, y, z is given, it will have to search for the closest cell included in a well. The name of the well could be provided as an optional argument as a hint.
* It should be possible to supply a `k` range (zone) that the pressure point must be within.
* If the requested time is not in the RFT file, it should interpolate linearly in time (warn appropriately)
* All data from the RFT record at the located point should be possible to return, not only the tubing/annulus/cell pressure
* Possibility to prioritize the correct zone over correct MD/z value.
* Related feature: Extract watercut/GOR for a zone (requires inflow pr. connection in the RFT/PLT dataset)

**Comment by anders-kiaer** [comment]
Is this planned to read the Eclipse/Flow/[your simulator] generated `RFT` file? I think then `eclRftFile`  from `ecl` then dicates that we need well name and time at least - if I remember correctly.

Are we thinking optionally also returning block pressures here (e.g. for comparison)?

Adding @EivindBakken also the discussion.

**Comment by berland** [comment]
The `rft2df` module wraps around libecl's code for RFT files already. The function here would have to search through the RFT/cell data if only x,y,z is given. 

I am not thinking block pressures, this is more or less handled already by the `grid2df` module handling UNRST files.

**Comment by anders-kiaer** [comment]
So you are here thinking of a convenience function (compared to using `rft2df` directly)?

**Comment by berland** [comment]
Yes. rft2df and grid2df already gives out the information needed.

**Comment by EivindBakken** [comment]
A general comment (that also might relate to grid2df and/or rft2df): Can also saturations be handled? (ref GENDATA_RFT vs GENDATA_RFTSAT) I believe saturation observations in wells are underutilized observations

**Comment by berland** [comment]
Yes, they can! Check the updated feature list at the top.

**Comment by berland** [comment]
Dependent on #88

**Comment by berland** [comment]
This feature is covered by gendata_rft in semeio and will not be prioritized in ecl2df. Semeio outputs dataframes and/or CSV files.
