### ISSUE TITLE
Enable export with rich metadata in the FMU context

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/ecl2df#439]
To be further refined and described

Short-story:
- Current behavior with ecl2df + fmu-dataio is to export `csv`, then read same `csv` with new FORWARD_MODEL, then export again with metadata.
- Suggested:
  - Optional functionality in `ecl2df` that creates and attaches rich metadata on the FMU standard to outgoing exports
  - Calling fmu-dataio to do this (important, to keep in synch, no hardcoding of metadata in ecl2df)
  - Should be called by an optional argument in the ERT FORWARD_JOB context, e.g. `--metadata`

**Comment by perolavsvendsen** [comment]
Adding this issue as a placeholder for ongoing discussions, and for inclusion in Github projects.

**Comment by perolavsvendsen** [comment]
Offline refinement with @daniel-sol, based on draft PR #442:

Currently included features:
- Integrate fmu-dataio so that it is used to export data in ecl2df, allowing for the creation of rich metadata on FMU standard (solving this issue)
- Enable bulk export with metadata of multiple data types produced by the simulator, to avoid having to repeat the call to ecl2df multiple times.
  - Allow for use of config file to control the bulk export, i.e. global_variables/fmu-config.

Missing:
  - Allow for separate configuration input to fmu-dataio per datatype, e.g. the input arguments to ExportData may vary per export (this was the showstopper last time around). This is particularly important with respect to access control.

Plan:
- [ ] Enable export with fmu-dataio from `ecl2df` to produce rich metadata on FMU standard, without breaking changes to the existing ecl2df implementations/forward jobs --> New PR.
  - [ ] Allow for passing of keyword arguments to fmu-dataio, so that different calls to ecl2df can have different export settings (access, classification, folder, etc etc).

  Definition of Done:
  - End user of FMU can, with minimal effort, add export of rich metadata on ecl2df output using fmu-dataio.
  - No breaking changes, all existing usage of ecl2df will still function as expected.
  
> Current draft PR has an `ecl2csv` section in global_variables, containing various settings. Consider refactoring this to a richer format (e.g. `dict`) which can facilitate/expand to separate arguments to fmu-dataio for each data type.

- [ ] Separate issue describing the bulk export feature -> Separate PR
- [ ] Separate issue describing auto-detection of output name -> Separate PR

**Comment by daniel-sol** [comment]
This will not be implemented here. Will be part of fmu-sumo. See issue https://github.com/equinor/fmu-sumo/issues/197
