### ISSUE TITLE
[gruptree] Gruptree duplicated nodes

### ISSUE THREAD

**Issue by berland** [equinor/ecl2df#89]
Pretty-printing of gruptree does not seem to work if nodes are duplicated.

**Comment by berland** [comment]
![image](https://user-images.githubusercontent.com/306834/73449587-ca1ddf00-4363-11ea-8083-fd6eee8b42d9.png)

**Comment by berland** [comment]
![image](https://user-images.githubusercontent.com/306834/73449635-e91c7100-4363-11ea-9371-7042fbac989a.png)

**Comment by berland** [comment]
![image](https://user-images.githubusercontent.com/306834/73449652-f3d70600-4363-11ea-9469-4b8f1b303a6e.png)

**Comment by berland** [comment]
![image](https://user-images.githubusercontent.com/306834/73449680-02bdb880-4364-11ea-9ac2-6081c0958e2d.png)

**Comment by miroine** [comment]
would it be possible to handle the duplication and issue a warning ?

**Comment by berland** [comment]
Need a minimal example of the schedule section to reproduce, @miroine ?

**Comment by miroine** [comment]
@berland  ok ... I ll make you a quick test case

**Comment by berland** [comment]
@miroine any test case available?

**Comment by berland** [comment]
Code has been refactored in #253 , unless proven otherwise, this problem is assumed solved.
